### ISSUE TITLE
[Question] This says "on5ltetmo" but my phone is "on5ltemtr"

### ISSUE THREAD

**Issue by DRAWNBOX** [jcadduono/android_device_samsung_on5ltetmo#1]
Do you think this could work or.. should I just not?

**Comment by jcadduono** [comment]
Same phone different carrier apps yes this works for it it's even in init cpp

**Comment by jcadduono** [comment]
But this tree is only for building twrp won't work for full roms and it's already got an official device page up on twrp.me

**Comment by DRAWNBOX** [comment]
alright thanks
